const STORAGE_KEY='pv-beschaffungsassistent-v1';
const starterCatalog=[
 {id:'req-module',category:'PV-Module',name:'PV-Modul gemäss Projektanforderung',supplier:'',sku:'',unit:'Stk.',powerWp:450,description:'Monokristallines PV-Modul; Mindestleistung und Wirkungsgrad gemäss Projektvorgabe. Datenblatt, Konformität und Garantie beilegen.',url:'',kind:'requirement'},
 {id:'req-mount',category:'Unterkonstruktion',name:'Unterkonstruktion passend zur Dachart',supplier:'',sku:'',unit:'Set',powerWp:0,description:'Komplettes, für Dachaufbau und Wind-/Schneelasten geeignetes Montagesystem inklusive Verbinder, Befestiger, Schutzlagen und erforderlicher Ballastierung. Dachlastgrenzen einhalten.',url:'',kind:'requirement'},
 {id:'req-inverter',category:'Wechselrichter',name:'Wechselrichter passend zur Anlagenauslegung',supplier:'',sku:'',unit:'Stk.',powerWp:0,description:'Lieferung eines kompatiblen Wechselrichters einschliesslich erforderlicher Schutzeinrichtungen und Zubehör. Datenblatt und Konformitätsnachweis beilegen.',url:'',kind:'requirement'},
 {id:'req-optimizers',category:'Leistungsoptimierer',name:'Leistungsoptimierer (falls erforderlich)',supplier:'',sku:'',unit:'Stk.',powerWp:0,description:'Anzahl und Typ durch Anbieter anhand Modul-, String- und Wechselrichterauslegung bestimmen. Kompatibilität nachweisen.',url:'',kind:'requirement'},
 {id:'req-cable',category:'Kabel & Steckverbinder',name:'PV-Kabel, Steckverbinder und Kabelmanagement',supplier:'',sku:'',unit:'psch',powerWp:0,description:'Vollständiges, für die Umgebung geeignetes DC-Kabel- und Steckverbindermaterial einschliesslich Befestigung und Schutz. Steckverbinder systemkompatibel ausführen.',url:'',kind:'requirement'},
 {id:'req-protection',category:'Überspannungsschutz',name:'Überspannungsschutz AC/DC',supplier:'',sku:'',unit:'Set',powerWp:0,description:'Erforderlicher AC- und DC-Überspannungsschutz einschliesslich Gehäuse, Anschlussmaterial und Zubehör gemäss Anlagenkonzept.',url:'',kind:'requirement'},
 {id:'req-earth',category:'Erdung & Blitzschutz',name:'Erdung, Potentialausgleich und Systemzubehör',supplier:'',sku:'',unit:'psch',powerWp:0,description:'Erforderliche leitfähige Verbindungselemente und Zubehör zur Einbindung der PV-Anlage in das projektseitige Erdungs- und Blitzschutzkonzept.',url:'',kind:'requirement'}
];
const initial={project:{name:'Neues PV-Projekt',kwp:60,area:'',roof:'Flachdach',orientation:'Süd',requirements:''},catalog:starterCatalog,lines:[]};
let state=loadState();let supplierFilter='Alle';
function loadState(){try{return {...initial,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'),project:{...initial.project,...(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}').project||{})}}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
function esc(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function unitFor(item){return item.unit||'Stk.'}
function addCatalogLine(item){let qty='',status='open';if(item.category==='PV-Module'&&Number(state.project.kwp)>0&&Number(item.powerWp)>0){qty=Math.ceil(Number(state.project.kwp)*1000/Number(item.powerWp));status='review'}state.lines.push({id:crypto.randomUUID(),category:item.category,description:item.description||item.name,quantity:qty,unit:unitFor(item),quantityStatus:status,productLabel:[item.name,item.supplier,item.sku].filter(Boolean).join(' · '),url:item.url||'',productId:item.id});save();toast('Materialposition hinzugefügt')}
function addRequirement(item){state.lines.push({id:crypto.randomUUID(),category:item.category,description:item.description,quantity:'',unit:unitFor(item),quantityStatus:'open',productLabel:item.name==='PV-Modul gemäss Projektanforderung'?'Anbieterprodukt gemäss Anforderung':'',url:'',productId:item.id});save()}
function render(){
 const p=state.project;document.querySelector('#projectName').value=p.name||'';document.querySelector('#targetKwp').value=p.kwp||'';document.querySelector('#roofArea').value=p.area||'';document.querySelector('#roofType').value=p.roof||'Flachdach';document.querySelector('#orientation').value=p.orientation||'Süd';document.querySelector('#requirements').value=p.requirements||'';
 document.querySelector('#summaryProject').textContent=p.name||'PV-Projekt';document.querySelector('#summaryRoof').textContent=[p.roof,p.orientation].filter(Boolean).join(' · ');document.querySelector('#summaryKwp').textContent=p.kwp||'–';document.querySelector('#summaryLines').textContent=state.lines.length;document.querySelector('#footerCount').textContent=state.lines.length;document.querySelector('#summaryStatus').textContent=state.lines.length?`${state.lines.filter(x=>x.quantityStatus!=='fixed').length} Mengen zu prüfen`:'Noch keine Positionen';
 const moduleLine=state.lines.find(x=>x.category==='PV-Module'&&Number(x.quantity)>0);document.querySelector('#summaryModules').textContent=moduleLine?`${moduleLine.quantity} Module · Richtwert, zu prüfen`:'Modulanzahl offen';
 document.querySelector('#catalogCount').textContent=state.catalog.length;renderCatalog();renderLines();
}
function renderCatalog(){const suppliers=['Alle',...new Set(state.catalog.map(x=>x.supplier).filter(Boolean))];const chips=document.querySelector('#supplierChips');chips.innerHTML=suppliers.map(x=>`<button class="chip ${supplierFilter===x?'active':''}" data-supplier="${esc(x)}">${esc(x)}</button>`).join('');chips.querySelectorAll('button').forEach(b=>b.onclick=()=>{supplierFilter=b.dataset.supplier;renderCatalog()});const term=document.querySelector('#searchCatalog').value.toLocaleLowerCase('de-CH');const items=state.catalog.filter(x=>(supplierFilter==='Alle'||x.supplier===supplierFilter)&&[x.name,x.supplier,x.sku,x.category,x.description].join(' ').toLocaleLowerCase('de-CH').includes(term));document.querySelector('#catalogList').innerHTML=items.length?items.map(x=>`<article class="catalog-item"><div class="catalog-item-head"><strong>${esc(x.name)}</strong><span class="catalog-tag">${esc(x.category)}</span></div><p>${esc(x.description||'')}</p><div class="catalog-meta"><span>${esc(x.supplier||'Neutrale Anforderung')}${x.sku?' · '+esc(x.sku):''}</span><button class="mini-add" data-add="${esc(x.id)}">+ Ins LV</button></div></article>`).join(''):'<p class="panel-footnote">Keine passenden Einträge. Importiere einen Shopkatalog oder ergänze einen Eintrag.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const item=state.catalog.find(x=>x.id===b.dataset.add);if(item?.kind==='requirement')addRequirement(item);else if(item)addCatalogLine(item)})}
function renderLines(){const body=document.querySelector('#tenderRows');document.querySelector('#emptyState').hidden=state.lines.length>0;body.innerHTML=state.lines.map((x,i)=>`<tr><td class="pos">${String(i+1).padStart(2,'0')}</td><td class="desc-cell"><strong>${esc(x.category)}</strong>${esc(x.description)}${x.quantityStatus==='review'?'<br><small>Richtwert aus Ziel-Leistung; String- und Layoutplanung prüfen.</small>':''}</td><td>${x.quantityStatus==='fixed'?`<input class="qty-input" data-qty="${esc(x.id)}" type="number" min="0" step="any" value="${esc(x.quantity)}">`:`<span class="qty-open">${x.quantityStatus==='review'&&x.quantity?esc(x.quantity)+' · prüfen':'Menge offen'}</span>`}</td><td>${esc(x.unit||'')}</td><td class="vendor-cell">${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.productLabel||'Produktlink')}</a>`:esc(x.productLabel||'Durch Anbieter zu offerieren')}</td><td><button class="remove-row" data-remove="${esc(x.id)}" aria-label="Position entfernen">×</button></td></tr>`).join('');body.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.lines=state.lines.filter(x=>x.id!==b.dataset.remove);save()});body.querySelectorAll('[data-qty]').forEach(inp=>inp.onchange=()=>{const l=state.lines.find(x=>x.id===inp.dataset.qty);l.quantity=inp.value;l.quantityStatus='fixed';save()})}
function toast(message){const t=document.createElement('div');t.className='toast';t.textContent=message;document.body.append(t);setTimeout(()=>t.remove(),2600)}
function csvCell(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function exportCsv(){if(!state.lines.length){toast('Bitte zuerst Materialpositionen erfassen');return}const rows=[['Projekt',state.project.name],['Ziel-Leistung kWp',state.project.kwp],['Dachart',state.project.roof],['Ausrichtung',state.project.orientation],['Besondere Vorgaben',state.project.requirements],[],['Pos.','Kategorie','Leistungsbeschrieb','Menge','Einheit','Produkt / Lieferant','Artikelnummer','Produktlink','Stückpreis (Anbieter)','Summe (Anbieter)','Prüfhinweis']];state.lines.forEach((x,i)=>{const product=state.catalog.find(p=>p.id===x.productId);rows.push([String(i+1).padStart(2,'0'),x.category,x.description,x.quantityStatus==='fixed'?x.quantity:'',x.unit,x.productLabel,product?.sku||'',x.url,'','',x.quantityStatus==='fixed'?'':'Menge / Auslegung durch Anbieter oder Fachplanung bestätigen'])});const content='\uFEFF'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n');const blob=new Blob([content],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${(state.project.name||'PV-Leistungsverzeichnis').replace(/[^\p{L}\p{N}-]+/gu,'-')}-Material.csv`;a.click();URL.revokeObjectURL(a.href);toast('Excel-kompatible Ausschreibung exportiert')}
function openDialog(id){document.getElementById(id).showModal()}
function resetProject(){if(!confirm('Neues Projekt beginnen? Projektangaben und Positionen werden zurückgesetzt. Der Produktkatalog bleibt erhalten.'))return;state.project={...initial.project};state.lines=[];save();toast('Neues Projekt bereit')}
document.querySelectorAll('#projectName,#targetKwp,#roofArea,#roofType,#orientation,#requirements').forEach(el=>el.addEventListener('change',()=>{state.project={name:document.querySelector('#projectName').value,kwp:document.querySelector('#targetKwp').value,area:document.querySelector('#roofArea').value,roof:document.querySelector('#roofType').value,orientation:document.querySelector('#orientation').value,requirements:document.querySelector('#requirements').value};save()}));
document.querySelector('#searchCatalog').oninput=renderCatalog;document.querySelector('#addProduct').onclick=()=>openDialog('productDialog');document.querySelector('#addLine').onclick=()=>openDialog('lineDialog');document.querySelector('#emptyAdd').onclick=()=>openDialog('lineDialog');document.querySelector('#exportCsv').onclick=exportCsv;document.querySelector('#newProject').onclick=resetProject;document.querySelector('#importCatalog').onclick=()=>document.querySelector('#catalogFile').click();
document.querySelector('#saveProduct').onclick=e=>{e.preventDefault();const f=new FormData(document.querySelector('#productForm'));const item={id:crypto.randomUUID(),name:f.get('name'),supplier:f.get('supplier'),category:f.get('category'),sku:f.get('sku'),unit:f.get('unit')||'Stk.',powerWp:Number(f.get('powerWp'))||0,description:f.get('description'),url:f.get('url'),kind:'product'};state.catalog.push(item);document.querySelector('#productForm').reset();document.querySelector('#productDialog').close();save();toast('Produkt im Katalog gespeichert')};
document.querySelector('#saveLine').onclick=e=>{e.preventDefault();const f=new FormData(document.querySelector('#lineForm'));state.lines.push({id:crypto.randomUUID(),category:f.get('category'),description:f.get('description'),quantity:f.get('quantity'),unit:f.get('unit')||'Stk.',quantityStatus:f.get('quantityStatus'),productLabel:f.get('productLabel'),url:''});document.querySelector('#lineForm').reset();document.querySelector('#lineDialog').close();save();toast('Position ins Leistungsverzeichnis übernommen')};
document.querySelector('#catalogFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const raw=(await file.text()).replace(/^\uFEFF/,'');const lines=raw.split(/\r?\n/).filter(Boolean);const delim=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?';':',';const parse=row=>row.split(delim).map(v=>v.trim().replace(/^"|"$/g,'').replaceAll('""','"'));const headers=parse(lines.shift()).map(x=>x.toLowerCase());const aliases={name:['name','produkt','produktname'],supplier:['lieferant','supplier','shop'],category:['kategorie','category'],sku:['artikelnummer','sku','artikel-nr'],unit:['einheit','unit'],powerWp:['leistung wp','powerwp','wp'],description:['beschreibung','technische beschreibung','description'],url:['url','link','produktlink']};const index=key=>headers.findIndex(h=>aliases[key].includes(h));const items=lines.map(row=>{const values=parse(row);const get=key=>index(key)>=0?values[index(key)]||'':'';return{id:crypto.randomUUID(),name:get('name'),supplier:get('supplier'),category:get('category')||'Sonstiges Material',sku:get('sku'),unit:get('unit')||'Stk.',powerWp:Number(get('powerWp'))||0,description:get('description'),url:get('url'),kind:'product'}}).filter(x=>x.name);state.catalog.push(...items);save();e.target.value='';toast(`${items.length} Produkte importiert`)};

window.addEventListener('pv-plan-result',e=>{
 const d=e.detail||{};
 const items=[
  {category:'PV-Module',description:'PV-Module gemäss Dachplan, Abmessung und Ausrichtung; Stückzahl aus geometrischer Vorplanung. Modultyp, Randabstände und Stringauslegung durch Fachplanung bestätigen.',quantity:d.modules,unit:'Stk.',quantityStatus:'review',productLabel:'Modulformat gemäss Planungsannahme'},
  {category:'Unterkonstruktion',description:'Lieferung und Montage der Unterkonstruktion passend zum gewählten Dachsystem. Vorläufige Modul-Belegungsfläche gemäss Dachplan; vollständiges System inklusive Verbinder und Befestiger durch Anbieter dimensionieren.',quantity:Number(d.moduleArea||0).toFixed(1),unit:'m²',quantityStatus:'review',productLabel:'System durch Anbieter festlegen'},
  {category:'Dacharbeiten',description:'Bearbeitungs- bzw. Belegungsbereich gemäss markierter nutzbarer Dachfläche. Dachaufbau, Schutzlagen, Durchdringungen und Zugangs-/Brandschutzwege vor Ort prüfen.',quantity:Number(d.roofArea||0).toFixed(1),unit:'m²',quantityStatus:'review',productLabel:'Flächenrichtwert aus Planzeichnung'}
 ];
 items.forEach(x=>state.lines.push({id:crypto.randomUUID(),...x,url:''}));
 save();toast('Modul- und Flächenmengen ins Leistungsverzeichnis übernommen');
});

render();
