(()=> {
const KEY='pv-plan-meta-v1', DB='pv-plan-files-v1';
const $=s=>document.querySelector(s);
let meta=JSON.parse(localStorage.getItem(KEY)||'{}'), image=null, dims={w:0,h:0}, mode='area', points=[], exclusions=[], calibration=[];
const box=$('#planCanvas'), svg=$('#planOverlay'), img=$('#planImage');
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function fileStore(method,value){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('files','readwrite'),s=tx.objectStore('files'),r=method==='put'?s.put(value,'plan'):s.get('plan');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function save(){localStorage.setItem(KEY,JSON.stringify(meta))}
function say(t){$('#planStatus').textContent=t}
function xy(e){const r=svg.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]}
function path(poly){return poly.map((p,i)=>(i?'L':'M')+(p[0]*1000)+','+(p[1]*1000)).join(' ')+(poly.length>2?' Z':'')}
function redraw(){if(!svg)return;svg.innerHTML='';if(meta.area)svg.insertAdjacentHTML('beforeend','<path class="plan-area" d="'+path(meta.area)+'"/>');(meta.exclusions||[]).forEach(p=>svg.insertAdjacentHTML('beforeend','<path class="plan-exclusion" d="'+path(p)+'"/>'));(meta.modules||[]).forEach(p=>svg.insertAdjacentHTML('beforeend','<polygon class="plan-module" points="'+p.map(x=>x[0]*1000+','+x[1]*1000).join(' ')+'"/>'));const active=mode==='area'?points:mode==='exclude'?exclusions:calibration;if(active.length){svg.insertAdjacentHTML('beforeend','<path class="plan-draft" d="'+path(active)+'"/>');active.forEach(p=>svg.insertAdjacentHTML('beforeend','<circle class="plan-point" cx="'+p[0]*1000+'" cy="'+p[1]*1000+'" r="5"/>'))}}
function finishDraw(){if(mode==='calibrate'){say('Für den Massstab zwei Punkte anklicken; die Strecke wird direkt übernommen.');return}const target=mode==='area'?'area':'exclusions';if((mode==='area'?points:exclusions).length<3){say('Bitte mindestens 3 Eckpunkte setzen.');return}meta[target]=[...(mode==='area'?points:exclusions)];if(mode==='area')points=[];else exclusions=[];meta.modules=[];save();redraw();calculate()}
function mpp(){return meta.mpp||0}
function polyArea(poly){let a=0;for(let i=0,j=poly.length-1;i<poly.length;j=i++)a+=poly[j][0]*poly[i][1]-poly[i][0]*poly[j][1];return Math.abs(a)/2*dims.w*dims.h*mpp()**2}
function inside(p,poly){let c=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let a=poly[i],b=poly[j];if(((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0]))c=!c}return c}
function layout(){if(!meta.area||!mpp()){say('Fläche zeichnen und Massstab festlegen.');return}const w=Number($('#moduleW').value)/1000,h=Number($('#moduleH').value)/1000,g=Number($('#moduleGap').value)/100,rot=Number($('#arrayRotation').value)*Math.PI/180;if(!(w>0&&h>0))return;const poly=meta.area.map(p=>[p[0]*dims.w*mpp(),p[1]*dims.h*mpp()]);const ex=(meta.exclusions||[]).map(a=>a.map(p=>[p[0]*dims.w*mpp(),p[1]*dims.h*mpp()]));const minX=Math.min(...poly.map(p=>p[0])),maxX=Math.max(...poly.map(p=>p[0])),minY=Math.min(...poly.map(p=>p[1])),maxY=Math.max(...poly.map(p=>p[1]));let best=[];
for(const [pw,ph] of [[w,h],[h,w]]){const c=Math.cos(rot),s=Math.sin(rot),hx=Math.abs(c*pw/2)+Math.abs(s*ph/2),hy=Math.abs(s*pw/2)+Math.abs(c*ph/2);for(let y=minY+hy;y<=maxY-hy;y+=2*hy+g){for(let x=minX+hx;x<=maxX-hx;x+=2*hx+g){const corners=[[-pw/2,-ph/2],[pw/2,-ph/2],[pw/2,ph/2],[-pw/2,ph/2]].map(([a,b])=>[x+a*c-b*s,y+a*s+b*c]);const blocked=ex.some(area=>corners.some(p=>inside(p,area))||area.some(p=>{const dx=p[0]-x,dy=p[1]-y;return Math.abs(dx*c+dy*s)<pw/2&&Math.abs(-dx*s+dy*c)<ph/2}));if(corners.every(p=>inside(p,poly))&&!blocked)best.push(corners.map(p=>[p[0]/mpp()/dims.w,p[1]/mpp()/dims.h]))}}}
meta.modules=best;meta.moduleW=w;meta.moduleH=h;meta.gap=g;save();redraw();calculate();say(best.length+' Module passen rechnerisch in die markierte Fläche.')}
function calculate(){if(!dims.w)return;const raw=meta.area?polyArea(meta.area):0,blocked=(meta.exclusions||[]).reduce((a,p)=>a+polyArea(p),0),area=Math.max(0,raw-blocked),cover=(meta.modules||[]).length*(meta.moduleW||Number($('#moduleW').value)/1000)*(meta.moduleH||Number($('#moduleH').value)/1000);$('#planAreaResult').textContent=area?area.toFixed(1)+' m²':'–';$('#moduleCountResult').textContent=(meta.modules||[]).length||'–';$('#moduleAreaResult').textContent=cover?cover.toFixed(1)+' m²':'–';if(area){const v=$('#roofArea');v.value=area.toFixed(1);v.dispatchEvent(new Event('change',{bubbles:true}))}}
async function loadSaved(){try{const f=await fileStore('get');if(f&&f.size){image=URL.createObjectURL(f);img.onload=()=>{dims={w:img.naturalWidth,h:img.naturalHeight};box.hidden=false;redraw();calculate()};img.src=image}}catch{}}
$('#planFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')){say('Bitte den Plan als PNG oder JPG hochladen (PDF-Seite vorher als Bild exportieren).');return}await fileStore('put',f);meta={...meta,name:f.name,area:null,exclusions:[],modules:[],mpp:0};save();if(image)URL.revokeObjectURL(image);image=URL.createObjectURL(f);img.onload=()=>{dims={w:img.naturalWidth,h:img.naturalHeight};box.hidden=false;redraw();say('Plan geladen. Jetzt Massstab festlegen.');calculate()};img.src=image};
$('#planMode').onchange=e=>{mode=e.target.value;points=[];exclusions=[];calibration=[];redraw();say(mode==='calibrate'?'Zwei Punkte auf einer bekannten Strecke anklicken.':'Eckpunkte auf dem Plan anklicken; danach „Fläche abschliessen“.')};
svg.onclick=e=>{if(!dims.w)return;const p=xy(e);if(mode==='calibrate'){calibration.push([p[0]*dims.w,p[1]*dims.h]);redraw();if(calibration.length===2){const px=Math.hypot(calibration[1][0]-calibration[0][0],calibration[1][1]-calibration[0][1]);const real=Number($('#knownDistance').value);if(px&&real){meta.mpp=real/px;save();say('Massstab erfasst: 1 m entspricht '+(1/meta.mpp).toFixed(0)+' Bildpunkten.');calculate()}calibration=[]}}else{(mode==='area'?points:exclusions).push(p);redraw()}};
$('#finishPolygon').onclick=finishDraw;$('#clearDraft').onclick=()=>{points=[];exclusions=[];redraw()};$('#calculateLayout').onclick=layout;
$('#sendPlanToLv').onclick=()=>{const n=(meta.modules||[]).length;if(!n){say('Bitte zuerst eine Modulbelegung berechnen.');return}window.dispatchEvent(new CustomEvent('pv-plan-result',{detail:{modules:n,moduleArea:n*(meta.moduleW||0)*(meta.moduleH||0),roofArea:meta.area?polyArea(meta.area):0}}));say('Modul- und Flächenmengen wurden ins Leistungsverzeichnis übernommen.')};
$('#clearPlan').onclick=async()=>{if(!confirm('Plan und Markierungen entfernen?'))return;meta={};save();await fileStore('put',new Blob([]));img.removeAttribute('src');box.hidden=true;dims={w:0,h:0};$('#planAreaResult').textContent='–';$('#moduleCountResult').textContent='–';$('#moduleAreaResult').textContent='–';say('Kein Plan geladen.')};
$('#moduleW').onchange=layout;$('#moduleH').onchange=layout;$('#moduleGap').onchange=layout;$('#arrayRotation').onchange=layout;
loadSaved();
})();