(()=> {
const KEY='pv-plan-meta-v1', DB='pv-plan-files-v1';
const $=s=>document.querySelector(s);
let meta=JSON.parse(localStorage.getItem(KEY)||'{}'), image=null, dims={w:0,h:0}, mode='area', points=[], exclusions=[], calibration=[];
const box=$('#planCanvas'), svg=$('#planOverlay'), img=$('#planImage'), stage=$('#planStage'), dialog=$('#planDialog'), dialogTarget=$('#planDialogTarget');
dialogTarget.appendChild(document.querySelector('#planTools'));dialogTarget.appendChild(box);let zoom=1;
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function fileStore(method,value){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('files','readwrite'),s=tx.objectStore('files'),r=method==='put'?s.put(value,'plan'):s.get('plan');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function save(){localStorage.setItem(KEY,JSON.stringify(meta))}
function requireCalibration(clearSelection=false){meta.mpp=0;meta.modules=[];if(clearSelection){meta.area=null;meta.exclusions=[]}mode='calibrate';points=[];exclusions=[];calibration=[];$('#planMode').value='area';save();redraw();calculate();say('Bitte zuerst den Massstab kalibrieren: zwei Punkte auf einer bekannten Strecke anklicken.')}
async function renderPdf(file,pageNo){const lib=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.mjs');lib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.worker.mjs';const pdf=await lib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;meta.pdfPages=pdf.numPages;meta.pdfPage=Math.max(1,Math.min(pdf.numPages,Number(pageNo)||1));$('#pdfPage').max=pdf.numPages;$('#pdfPage').value=meta.pdfPage;$('#pdfPageCount').textContent='von '+pdf.numPages;$('#pdfControls').hidden=false;const page=await pdf.getPage(meta.pdfPage),v=page.getViewport({scale:1}),scale=Math.min(2.4,2800/Math.max(v.width,v.height)),viewport=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvas,canvasContext:canvas.getContext('2d'),viewport}).promise;const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));showImage(blob)}
function showImage(blob){if(image)URL.revokeObjectURL(image);image=URL.createObjectURL(blob);img.onload=()=>{dims={w:img.naturalWidth,h:img.naturalHeight};box.hidden=false;redraw();calculate()};img.src=image}
function say(t){$('#planStatus').textContent=t;$('#planDialogStatus').textContent=t}
function xy(e){const r=svg.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]}
function path(poly){return poly.map((p,i)=>(i?'L':'M')+(p[0]*1000)+','+(p[1]*1000)).join(' ')+(poly.length>2?' Z':'')}
function redraw(){if(!svg)return;svg.innerHTML='';if(meta.area)svg.insertAdjacentHTML('beforeend','<path class="plan-area" d="'+path(meta.area)+'"/>');(meta.exclusions||[]).forEach(p=>svg.insertAdjacentHTML('beforeend','<path class="plan-exclusion" d="'+path(p)+'"/>'));(meta.modules||[]).forEach(p=>svg.insertAdjacentHTML('beforeend','<polygon class="plan-module" points="'+p.map(x=>x[0]*1000+','+x[1]*1000).join(' ')+'"/>'));const active=mode==='area'?points:mode==='exclude'?exclusions:calibration;if(active.length){svg.insertAdjacentHTML('beforeend','<path class="plan-draft" d="'+path(active)+'"/>');active.forEach(p=>svg.insertAdjacentHTML('beforeend','<circle class="plan-point" cx="'+p[0]*1000+'" cy="'+p[1]*1000+'" r="5"/>'))}}
function finishDraw(){if(!mpp()){requireCalibration();return}if(mode==='calibrate'){say('Für den Massstab zwei Punkte anklicken; die Strecke wird direkt übernommen.');return}const target=mode==='area'?'area':'exclusions';if((mode==='area'?points:exclusions).length<3){say('Bitte mindestens 3 Eckpunkte setzen.');return}meta[target]=[...(mode==='area'?points:exclusions)];if(mode==='area')points=[];else exclusions=[];meta.modules=[];save();redraw();calculate()}
function applyZoom(){stage.style.width=(zoom*100)+'%';$('#zoomLabel').textContent=Math.round(zoom*100)+'%'}
function openPlan(recalibrate=false){if(!dims.w){say('Bitte zuerst einen Plan laden.');return}if(recalibrate)requireCalibration();else if(!mpp()){mode='calibrate';say('Bitte zuerst den Massstab kalibrieren.')}dialog.showModal();applyZoom()}
$('#calibrateScale').onclick=()=>openPlan(true);$('#openPlan').onclick=()=>openPlan(false);
$('#closePlan').onclick=()=>dialog.close();$('#zoomIn').onclick=()=>{zoom=Math.min(3,zoom+0.2);applyZoom()};
$('#zoomOut').onclick=()=>{zoom=Math.max(0.5,zoom-0.2);applyZoom()};$('#zoomFit').onclick=()=>{zoom=1;applyZoom()};
function mpp(){return meta.mpp||0}
function polyArea(poly){let a=0;for(let i=0,j=poly.length-1;i<poly.length;j=i++)a+=poly[j][0]*poly[i][1]-poly[i][0]*poly[j][1];return Math.abs(a)/2*dims.w*dims.h*mpp()**2}
function inside(p,poly){let c=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let a=poly[i],b=poly[j];if(((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0]))c=!c}return c}
function layout(){if(!meta.area||!mpp()){say('Fläche zeichnen und Massstab festlegen.');return}const w=Number($('#moduleW').value)/1000,h=Number($('#moduleH').value)/1000,g=Number($('#moduleGap').value)/100,rot=Number($('#arrayRotation').value)*Math.PI/180;if(!(w>0&&h>0))return;const poly=meta.area.map(p=>[p[0]*dims.w*mpp(),p[1]*dims.h*mpp()]);const ex=(meta.exclusions||[]).map(a=>a.map(p=>[p[0]*dims.w*mpp(),p[1]*dims.h*mpp()]));const minX=Math.min(...poly.map(p=>p[0])),maxX=Math.max(...poly.map(p=>p[0])),minY=Math.min(...poly.map(p=>p[1])),maxY=Math.max(...poly.map(p=>p[1]));let best=[];
for(const [pw,ph] of [[w,h],[h,w]]){const candidate=[],c=Math.cos(rot),s=Math.sin(rot),hx=Math.abs(c*pw/2)+Math.abs(s*ph/2),hy=Math.abs(s*pw/2)+Math.abs(c*ph/2);for(let y=minY+hy;y<=maxY-hy;y+=2*hy+g){for(let x=minX+hx;x<=maxX-hx;x+=2*hx+g){const corners=[[-pw/2,-ph/2],[pw/2,-ph/2],[pw/2,ph/2],[-pw/2,ph/2]].map(([a,b])=>[x+a*c-b*s,y+a*s+b*c]);const blocked=ex.some(area=>corners.some(p=>inside(p,area))||area.some(p=>{const dx=p[0]-x,dy=p[1]-y;return Math.abs(dx*c+dy*s)<pw/2&&Math.abs(-dx*s+dy*c)<ph/2}));if(corners.every(p=>inside(p,poly))&&!blocked)candidate.push(corners.map(p=>[p[0]/mpp()/dims.w,p[1]/mpp()/dims.h]))}}if(candidate.length>best.length)best=candidate}
meta.modules=best;meta.moduleW=w;meta.moduleH=h;meta.gap=g;save();redraw();calculate();say(best.length+' Module passen rechnerisch in die markierte Fläche.')}
function calculate(){if(!dims.w)return;const raw=meta.area?polyArea(meta.area):0,blocked=(meta.exclusions||[]).reduce((a,p)=>a+polyArea(p),0),area=Math.max(0,raw-blocked),cover=(meta.modules||[]).length*(meta.moduleW||Number($('#moduleW').value)/1000)*(meta.moduleH||Number($('#moduleH').value)/1000);$('#planAreaResult').textContent=area?area.toFixed(1)+' m²':'–';$('#moduleCountResult').textContent=(meta.modules||[]).length||'–';$('#moduleAreaResult').textContent=cover?cover.toFixed(1)+' m²':'–';if(area){const v=$('#roofArea');v.value=area.toFixed(1);v.dispatchEvent(new Event('change',{bubbles:true}))}}
const yieldDefaults={lat:'',lon:'',tilt:'30',loss:'14'};
function loadYieldSettings(){const y={...yieldDefaults,...(meta.yieldSettings||{})};$('#yieldLat').value=y.lat;$('#yieldLon').value=y.lon;$('#yieldTilt').value=y.tilt;$('#yieldLoss').value=y.loss;updateYieldButtons()}
function saveYieldSettings(){meta.yieldSettings={lat:$('#yieldLat').value,lon:$('#yieldLon').value,tilt:$('#yieldTilt').value,loss:$('#yieldLoss').value};save()}
function updateYieldButtons(){const eastWest=$('#orientation').value==='Ost-West';$('#openPvgis').hidden=eastWest;$('#openPvgisEast').hidden=!eastWest;$('#openPvgisWest').hidden=!eastWest}
function pvgisUrl(aspect,power){const latText=$('#yieldLat').value.trim(),lonText=$('#yieldLon').value.trim(),lat=Number(latText),lon=Number(lonText),tilt=Number($('#yieldTilt').value),loss=Number($('#yieldLoss').value);if(!latText||!lonText||!Number.isFinite(lat)||lat<-90||lat>90||!Number.isFinite(lon)||lon<-180||lon>180||!(tilt>=0&&tilt<=90)||!(loss>=0&&loss<=50)||!(power>0)){say('Bitte gültige Koordinaten, Dachneigung, Verluste und Ziel-Leistung eingeben.');return''}const q=new URLSearchParams({lat:String(lat),lon:String(lon),peakpower:String(power),loss:String(loss),fixed:'1',angle:String(tilt),aspect:String(aspect),mountingplace:'building',pvtechchoice:'crystSi',usehorizon:'1',outputformat:'json'});return 'https://re.jrc.ec.europa.eu/api/v5_3/PVcalc?'+q.toString()}
function launchPvgis(aspect,power){saveYieldSettings();const url=pvgisUrl(aspect,power);if(url)window.open(url,'_blank','noopener')}
$('#openPvgis').onclick=()=>{const p=Number($('#targetKwp').value),dirs={Süd:0,Südost:-45,Ost:-90,Nordost:-135,Nord:180,Nordwest:135,West:90,Südwest:45},d=dirs[$('#orientation').value];if(d===undefined){say('Für die Ertragsprognose bitte eine Himmelsrichtung oder Ost-West auswählen.');return}launchPvgis(d,p)};
$('#openPvgisEast').onclick=()=>launchPvgis(-90,Number($('#targetKwp').value)/2);$('#openPvgisWest').onclick=()=>launchPvgis(90,Number($('#targetKwp').value)/2);
['yieldLat','yieldLon','yieldTilt','yieldLoss'].forEach(id=>$('#'+id).addEventListener('change',saveYieldSettings));$('#orientation').addEventListener('change',updateYieldButtons);
loadYieldSettings();
async function loadSaved(){try{const f=await fileStore('get');if(f&&f.size){if(f.type==='application/pdf'){try{await renderPdf(f,meta.pdfPage||1)}catch{say('PDF konnte nicht geladen werden. Internetverbindung für die PDF-Anzeige prüfen.')}}else showImage(f);requireCalibration()}}catch{}}
$('#planFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const isPdf=f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf');if(!isPdf&&!f.type.startsWith('image/')){say('Bitte ein Bild oder eine PDF-Datei auswählen.');return}await fileStore('put',f);meta={...meta,name:f.name,pdfPage:1,area:null,exclusions:[],modules:[],mpp:0};save();try{if(isPdf)await renderPdf(f,1);else{$('#pdfControls').hidden=true;showImage(f)}requireCalibration(true)}catch(err){say('PDF-Anzeige fehlgeschlagen. Bitte Verbindung prüfen oder Plan als Bild laden.')}};
$('#showPdfPage').onclick=async()=>{const f=await fileStore('get');if(f?.type==='application/pdf'){try{await renderPdf(f,$('#pdfPage').value);requireCalibration(true)}catch{say('Diese PDF-Seite konnte nicht angezeigt werden.')}}};
$('#planMode').onchange=e=>{if(e.target.value!=='calibrate'&&!mpp()){requireCalibration();return}mode=e.target.value;points=[];exclusions=[];calibration=[];redraw();say(mode==='calibrate'?'Zwei Punkte auf einer bekannten Strecke anklicken.':'Eckpunkte auf dem Plan anklicken; danach „Fläche abschliessen“.')};
svg.onclick=e=>{if(!dims.w)return;const p=xy(e);if(mode==='calibrate'){calibration.push([p[0]*dims.w,p[1]*dims.h]);redraw();if(calibration.length===2){const px=Math.hypot(calibration[1][0]-calibration[0][0],calibration[1][1]-calibration[0][1]);const real=Number($('#knownDistance').value);if(px&&real>0){meta.mpp=real/px;save();mode='area';$('#planMode').value='area';say('Massstab kalibriert. Jetzt die nutzbare Fläche markieren.');calculate()}else say('Bitte eine positive Referenzstrecke eingeben und zwei unterschiedliche Punkte anklicken.');calibration=[];redraw()}}else{if(!mpp()){requireCalibration();return}(mode==='area'?points:exclusions).push(p);redraw()}};
$('#finishPolygon').onclick=finishDraw;$('#clearDraft').onclick=()=>{points=[];exclusions=[];redraw()};$('#calculateLayout').onclick=layout;
$('#sendPlanToLv').onclick=()=>{const n=(meta.modules||[]).length;if(!n){say('Bitte zuerst eine Modulbelegung berechnen.');return}window.dispatchEvent(new CustomEvent('pv-plan-result',{detail:{modules:n,moduleArea:n*(meta.moduleW||0)*(meta.moduleH||0),roofArea:meta.area?polyArea(meta.area):0}}));say('Modul- und Flächenmengen wurden ins Leistungsverzeichnis übernommen.')};
async function resetPlan(){meta={};save();mode='area';$('#planMode').value='area';zoom=1;applyZoom();if(dialog.open)dialog.close();await fileStore('put',new Blob([]));img.removeAttribute('src');$('#pdfControls').hidden=true;box.hidden=true;dims={w:0,h:0};$('#planAreaResult').textContent='–';$('#moduleCountResult').textContent='–';$('#moduleAreaResult').textContent='–';say('Kein Plan geladen.')}
$('#clearPlan').onclick=async()=>{if(!confirm('Plan und Markierungen entfernen?'))return;await resetPlan()};window.addEventListener('pv-new-project',resetPlan);
$('#modulePreset').onchange=()=>{const m=$('#modulePreset').value;if(m!=='custom'){const a=m.split('x');$('#moduleH').value=a[0];$('#moduleW').value=a[1]}layout()};$('#moduleW').onchange=()=>{$('#modulePreset').value='custom';layout()};$('#moduleH').onchange=()=>{$('#modulePreset').value='custom';layout()};$('#moduleGap').onchange=layout;$('#arrayRotation').onchange=layout;
loadSaved();
})();